### PR TITLE
92 -> 94 on acid3

### PR DESCRIPTION
**Pull request by gennaroterry**

### CODE REVIEW

**Comment by gennaroterry** [comment]
Some requests to the /scramjet/* endpoints are bypassing the Service Worker and directly hitting the server. When that problem is solved, you can get 97 on Acid3.

**Comment by velzie** [comment]
> Some requests to the /scramjet/* endpoints are bypassing the Service Worker and directly hitting the server. When that problem is solved, you can get 97 on Acid3.

this is a browser bug, there's not much we can do about it

**Comment by gennaroterry** [comment]
> > Some requests to the /scramjet/* endpoints are bypassing the Service Worker and directly hitting the server. When that problem is solved, you can get 97 on Acid3.
> 
> this is a browser bug, there's not much we can do about it

As a temporary workaround, 
we can set up the server to act as a simple, old-school proxy for these requests.  

```
fastify.get('/scramjet/*', async (request, reply) => {
// remove some headers from client
// send to dest.
// remove some headers from server and then send back.
}
```

**Comment by velzie** [comment]
the server as in the dev server? which isn't exported or used anywhere?
definitely out of scope for the project 

i believe firefox ignores the w3c recommendation which actually makes it behave correctly. maybe it's worth opening an issue over on chromium

**Comment by gennaroterry** [comment]
> Is this about syncxhr?

This PR implements parse5 as a solution to address limitations in htmlparser2, specifically targeting Acid3 test 29 compliance. 


Additionally, There is a known issue where Chromium-based browsers bypass the service worker, sending requests directly to the backend server - a behavior that affects both Acid3 test 65(I can't quite recall the exact test number) and Cloudflare's turnstile JavaScript loading mechanism.

**Comment by gennaroterry** [comment]
> the server as in the dev server? which isn't exported or used anywhere?
> definitely out of scope for the project

Agreed, There is no good solution on the client side for chromium.

**Pull request closed without merging**
