### PR TITLE
replace config file with bootstrapper

### PR DESCRIPTION
**Pull request by ThinLiquid**
I'm proposing to replace the `scramjet.config.ts` with a bootstrapper. This bootstrapper is capable of loading up a configuration file, it also has support for custom codecs. I will explain how the custom codec system works:

1. The bootstrapper encodes the custom codec's into string values.
2. The codec strings are sent to the Service Worker using `postMessage`
3. The Service Worker decodes the function using `eval`
4. The codecs get sent to `ScramjetServiceWorker`
5. The codecs are merged with the built-in codecs, overriding if needed.
6. profit :3

I also did a little bit of code cleanup but its very minimal.

### CODE REVIEW

**Comment by thonkinator** [comment]
why did you delete rainbow6seige

**Comment by ThinLiquid** [comment]
> why did you delete rainbow6siege

I saw it as unnecessary... If you want I can bring it back.

**Comment by thonkinator** [comment]
please use pnpm next time or at least delete the `package-lock.json` file

**Comment by ThinLiquid** [comment]
> please use pnpm next time or at least delete the `package-lock.json` file

I will keep that in mind for next time!

**Comment by Avad3** [comment]
fix the DAMN BOOTSTRAPPER

**Comment by ThinLiquid** [comment]
right...

**Pull request closed without merging**
